FROM mcr.microsoft.com/dotnet/aspnet:7.0-jammy

# .NET envs
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# User envs
ARG USERNAME=app
ARG APP_NAME=app

# TZ/LANG envs
ENV TZ=America/Sao_Paulo
ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR.UTF-8
ENV LC_ALL pt_BR.UTF-8

# Build scripts
COPY script-base-debian-like.sh /tmp/script-base.sh
RUN sh -x /tmp/script-base.sh && rm /tmp/script-base.sh

ENV APP_DIR=/home/$USERNAME

COPY docker-entrypoint.sh $APP_DIR

EXPOSE 8080

USER $USERNAME

WORKDIR $APP_DIR

ENTRYPOINT ["/bin/sh", "docker-entrypoint.sh"]