FROM jacksonveroneze/aspnet:6.0-alpine

ENV AWS_XRAY_CONTEXT_MISSING=LOG_ERROR

USER root

RUN curl https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-linux-3.x.zip -o xray.zip && \
    unzip ./xray.zip && \
    mv xray /usr/bin/xray && \
    rm xray.zip

USER dotnet