FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine

ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_RUNNING_IN_CONTAINER=true
ENV ASPNETCORE_ENVIRONMENT=Production
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV TZ=America/Sao_Paulo
ENV LANG pt-BR
ENV LANGUAGE pt-BR

ARG USERNAME=dotnet
ARG USER_UID=12345
ARG USER_GID=23456

RUN apk add --no-cache icu-data-full icu-libs curl tzdata && \
    rm -rf /var/cache/apk/* && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

RUN adduser -D $USERNAME \
        && mkdir -p /etc/sudoers.d \
        && echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USERNAME \
        && chmod 0440 /etc/sudoers.d/$USERNAME

ENV APP_DIR=/home/$USERNAME/app

EXPOSE 80

USER $USERNAME

WORKDIR $APP_DIR