FROM jacksonveroneze/aspnet:7.0-debian

USER root

# Build scripts
COPY script-install-xray-debian-like.sh /tmp/script-install-xray.sh
RUN sh -x /tmp/script-install-xray.sh && rm /tmp/script-install-xray.sh

USER $USERNAME

# envs
ENV AWS_XRAY_CONTEXT_MISSING=LOG_ERROR

COPY docker-entrypoint.sh $APP_DIR

ENTRYPOINT ["/bin/sh", "docker-entrypoint.sh"]