name: Create Release

on:
  release:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  RELEASE: ${{ github.event.release.tag_name }}

jobs:
  generate-publish-docker:
    name: Generate and Publish Docker Image
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Base - Build and Push
        run: |
          cd Aspnet/Base
          ./build.sh
          ./create-tag.sh
          ./push.sh
        shell: bash