name: Create Release

on:
  release:
    types:
      - created

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  generate-publish-docker:
    name: Generate and Publish Docker Image
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build base images
        run: cd Aspnet && ./build-base-images.sh
        shell: bash

      - name: Push base images
        run: |
          docker tag jacksonveroneze/aspnet:7.0-alpine jacksonveroneze/aspnet:7.0-alpine-${{ github.event.release.tag_name }}
          docker tag jacksonveroneze/aspnet:7.0-ubuntu jacksonveroneze/aspnet:7.0-ubuntu-${{ github.event.release.tag_name }}
          docker tag jacksonveroneze/aspnet:7.0-debian jacksonveroneze/aspnet:7.0-debian-${{ github.event.release.tag_name }}
          
          docker push jacksonveroneze/aspnet:7.0-alpine-${{ github.event.release.tag_name }}          
          docker push jacksonveroneze/aspnet:7.0-ubuntu-${{ github.event.release.tag_name }}
          docker push jacksonveroneze/aspnet:7.0-debian-${{ github.event.release.tag_name }}

      - name: Build xray images
        run: cd Aspnet && ./build-xray-images.sh
        shell: bash

      - name: Push xray images
        run: |
          docker tag jacksonveroneze/aspnet:7.0-alpine-xray jacksonveroneze/aspnet:7.0-alpine-xray-${{ github.event.release.tag_name }}
          docker tag jacksonveroneze/aspnet:7.0-ubuntu-xray jacksonveroneze/aspnet:7.0-ubuntu-xray-${{ github.event.release.tag_name }}
          docker tag jacksonveroneze/aspnet:7.0-debian-xray jacksonveroneze/aspnet:7.0-debian-xray-${{ github.event.release.tag_name }}
          
          docker push jacksonveroneze/aspnet:7.0-alpine-xray-${{ github.event.release.tag_name }}
          docker push jacksonveroneze/aspnet:7.0-ubuntu-xray-${{ github.event.release.tag_name }}
          docker push jacksonveroneze/aspnet:7.0-debian-xray-${{ github.event.release.tag_name }}