FROM mcr.microsoft.com/dotnet/aspnet:6.0-jammy

# .NET envs
ENV ASPNETCORE_URLS=http://+:5000
ENV DOTNET_RUNNING_IN_CONTAINER=true
ENV ASPNETCORE_ENVIRONMENT=Production
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

# User envs
ARG USERNAME=dotnet
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Build scripts
COPY script-base.sh /
RUN sh -x script-base.sh && rm script-base.sh

# TZ/LANG envs
ENV TZ=America/Sao_Paulo
ENV LC_ALL pt_BR.UTF-8
ENV LANG pt_BR.UTF-8
ENV LANGUAGE pt_BR.UTF-8

ENV APP_DIR=/home/$USERNAME/app

EXPOSE 5000

USER $USERNAME

WORKDIR $APP_DIR