FROM mcr.microsoft.com/dotnet/aspnet:6.0-jammy

ENV ASPNETCORE_URLS=http://+:80
ENV DOTNET_RUNNING_IN_CONTAINER=true
ENV ASPNETCORE_ENVIRONMENT=Production
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV TZ=America/Sao_Paulo
ENV LANG pt-BR
ENV LANGUAGE pt-BR

ARG USERNAME=dotnet
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN apt update && apt install -y --force-yes --no-install-recommends tzdata curl wget && \
    apt clean && apt autoclean && apt autoremove && \
    rm -rf /var/lib/apt/lists/*

RUN echo $TZ > /etc/timezone && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd -r --uid $USER_UID --gid $USER_GID -m $USERNAME

ENV APP_DIR=/home/$USERNAME/app

EXPOSE 80

USER $USERNAME

WORKDIR $APP_DIR